# Site settings
author: Brent Bauman
title: Must.  Learn.  Computer.
header-img: img/home-bg.png
email: brentbauman86@gmail.com
copyright_name: Brent Bauman
description: > # this means to ignore newlines until "baseurl:"
  Destroying comfort in my quest for a new beginning 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  BrentBauman86

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
