# Site settings
title: Must.  Learn.  Computer.
header-img: img/home-bg.png
email: brentbauman86@gmail.com
copyright_name: BrentBauman86
description: > # this means to ignore newlines until "baseurl:"
  Destroying comfort in my quest to be proud of what I do
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  BrentBauman86
learn_profile: BrentBauman86
email_username: brentbauman86@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
